import spades from "../../../assets/spade.png";
import nuts from "../../../assets/nuts.png";
import ladder from "../../../assets/ladder.png";
import pink from "../../../assets/pink-paint.png";
import metal from "../../../assets/rusted-metal.png";
import screw from "../../../assets/screw.png";
import wheels from "../../../assets/wheels.png";
import brush from "../../../assets/white-brush.png";
import drill1 from "../../../assets/drill-device.png";
import drill2 from "../../../assets/drill-device2.png";
import bots from "../../../assets/bots.png";
import blue from "../../../assets/blue-paint.png";
import brick from "../../../assets/bricks.png";
import lightBlue from "../../../assets/lightBlue-paint.png";
import doubleLadder from "../../../assets/double-ladder.png";
import toolsBag from "../../../assets/tools-bag.png";

export const data = [
  {
    id: "construction chemical",
    img: pink,
    rate: "35",
    percent: "40",
    price: "1,500",
    previousPrice: "3000",
  },

  {
    id: "construction nuts",
    img: nuts,
    rate: "100",
    percent: "99",
    previousPrice: "2,500",
    price: "2000",
  },
  {
    id: "spades",
    img: spades,
    rate: "70",
    previousPrice: "6,500",
    percent: "67",
    price: "5,500",
  },
  {
    id: " ladders",
    img: ladder,
    rate: "59",
    percent: "35",
    price: "10,000",
    previousPrice: "12,000",
  },
  {
    id: "metals",
    img: metal,
    rate: "88",
    percent: "90",
    price: "45,000",
    previousPrice: "47,000",
  },
  {
    id: "construction chemical",
    img: lightBlue,
    rate: "65",
    percent: "25",
    price: "5000",
    previousPrice: "6000",
  },
  {
    id: "bots",
    img: bots,
    rate: "45",
    percent: "15",
    price: "4,500",
    previousPrice: "5000",
  },
  {
    id: "tools box",
    img: toolsBag,
    rate: "40",
    percent: "20",
    price: "15,000",
    previousPrice: "16,500",
  },
  {
    id: "double ladder",
    img: doubleLadder,
    rate: "99",
    percent: "70",
    price: "35,000",
    previousPrice: "37,000",
  },
  {
    id: "screw drivers",
    img: screw,
    rate: "50",
    percent: "35",
    price: "2,500",
    previousPrice: "3000",
  },
  {
    id: "drilling device",
    img: drill1,
    rate: "89",
    percent: "77",
    previousPrice: "80,000",
    price: "78,000",
  },
  {
    id: "drilling device",
    img: drill2,
    rate: "67",
    previousPrice: "67,00",
    percent: "67",
    price: "65,000",
  },
  {
    id: "wheel barrow",
    img: wheels,
    rate: "77",
    percent: "67",
    price: "16,000",
    previousPrice: "17,000",
  },
  {
    id: "brush",
    img: brush,
    rate: "45",
    percent: "12",
    price: "1000",
    previousPrice: "1,500",
  },
  {
    id: "construction chemicals",
    img: blue,
    rate: "98",
    percent: "78",
    price: "11,000",
    previousPrice: "12,000",
  },

  {
    id: "bricks",
    img: brick,
    rate: "55",
    percent: "55",
    price: "9,500",
    previousPrice: "10,000",
  },
  {
    id: "construction chemical",
    img: pink,
    rate: "35",
    percent: "40",
    price: "1,500",
    previousPrice: "3000",
  },

  {
    id: "construction nuts",
    img: nuts,
    rate: "100",
    percent: "99",
    previousPrice: "2,500",
    price: "2000",
  },
  {
    id: "spades",
    img: spades,
    rate: "70",
    previousPrice: "6,500",
    percent: "67",
    price: "5,500",
  },
  {
    id: " ladders",
    img: ladder,
    rate: "59",
    percent: "35",
    price: "10,000",
    previousPrice: "12,000",
  },
  {
    id: "metals",
    img: metal,
    rate: "88",
    percent: "90",
    price: "45,000",
    previousPrice: "47,000",
  },
  {
    id: "construction chemical",
    img: lightBlue,
    rate: "65",
    percent: "25",
    price: "5000",
    previousPrice: "6000",
  },
  {
    id: "bots",
    img: bots,
    rate: "45",
    percent: "15",
    price: "4,500",
    previousPrice: "5000",
  },
  {
    id: "tools box",
    img: toolsBag,
    rate: "40",
    percent: "20",
    price: "15,000",
    previousPrice: "16,500",
  },
  {
    id: "double ladder",
    img: doubleLadder,
    rate: "99",
    percent: "70",
    price: "35,000",
    previousPrice: "37,000",
  },
  {
    id: "screw drivers",
    img: screw,
    rate: "50",
    percent: "35",
    price: "2,500",
    previousPrice: "3000",
  },
  {
    id: "drilling device",
    img: drill1,
    rate: "89",
    percent: "77",
    previousPrice: "80,000",
    price: "78,000",
  },
  {
    id: "drilling device",
    img: drill2,
    rate: "67",
    previousPrice: "67,00",
    percent: "67",
    price: "65,000",
  },
  {
    id: "wheel barrow",
    img: wheels,
    rate: "77",
    percent: "67",
    price: "16,000",
    previousPrice: "17,000",
  },
  {
    id: "brush",
    img: brush,
    rate: "45",
    percent: "12",
    price: "1000",
    previousPrice: "1,500",
  },
  {
    id: "construction chemicals",
    img: blue,
    rate: "98",
    percent: "78",
    price: "11,000",
    previousPrice: "12,000",
  },

  {
    id: "bricks",
    img: brick,
    rate: "55",
    percent: "55",
    price: "9,500",
    previousPrice: "10,000",
  },
  {
    id: "construction chemical",
    img: pink,
    rate: "35",
    percent: "40",
    price: "1,500",
    previousPrice: "3000",
  },

  {
    id: "construction nuts",
    img: nuts,
    rate: "100",
    percent: "99",
    previousPrice: "2,500",
    price: "2000",
  },
  {
    id: "spades",
    img: spades,
    rate: "70",
    previousPrice: "6,500",
    percent: "67",
    price: "5,500",
  },
  {
    id: " ladders",
    img: ladder,
    rate: "59",
    percent: "35",
    price: "10,000",
    previousPrice: "12,000",
  },
  {
    id: "metals",
    img: metal,
    rate: "88",
    percent: "90",
    price: "45,000",
    previousPrice: "47,000",
  },
  {
    id: "construction chemical",
    img: lightBlue,
    rate: "65",
    percent: "25",
    price: "5000",
    previousPrice: "6000",
  },
  {
    id: "bots",
    img: bots,
    rate: "45",
    percent: "15",
    price: "4,500",
    previousPrice: "5000",
  },
  {
    id: "tools box",
    img: toolsBag,
    rate: "40",
    percent: "20",
    price: "15,000",
    previousPrice: "16,500",
  },
  {
    id: "double ladder",
    img: doubleLadder,
    rate: "99",
    percent: "70",
    price: "35,000",
    previousPrice: "37,000",
  },
  {
    id: "screw drivers",
    img: screw,
    rate: "50",
    percent: "35",
    price: "2,500",
    previousPrice: "3000",
  },
  {
    id: "drilling device",
    img: drill1,
    rate: "89",
    percent: "77",
    previousPrice: "80,000",
    price: "78,000",
  },
  {
    id: "drilling device",
    img: drill2,
    rate: "67",
    previousPrice: "67,00",
    percent: "67",
    price: "65,000",
  },
  {
    id: "wheel barrow",
    img: wheels,
    rate: "77",
    percent: "67",
    price: "16,000",
    previousPrice: "17,000",
  },
  {
    id: "brush",
    img: brush,
    rate: "45",
    percent: "12",
    price: "1000",
    previousPrice: "1,500",
  },
  {
    id: "construction chemicals",
    img: blue,
    rate: "98",
    percent: "78",
    price: "11,000",
    previousPrice: "12,000",
  },

  {
    id: "bricks",
    img: brick,
    rate: "55",
    percent: "55",
    price: "9,500",
    previousPrice: "10,000",
  },
];
